version: "3"

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # SSL 인증서 설정 추가
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=smc970417@email.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt" # 인증서 저장 경로
    networks:
      - network

  booksan_users:
    restart: on-failure
    build: .
    deploy:
      replicas: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      # CORS 설정을 하나로 합치기
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://www.booksan.shop,https://booksan.shop,https://board.booksan.shop,https://chat.booksan.shop"
      # CORS 미들웨어 적용
      - "traefik.http.routers.chat.middlewares=cors@docker"
      # 추가 CORS 헤더 설정
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
      # 나머지 설정들...
      - "traefik.http.routers.chat.rule=Host(`users.booksan.shop`)"
      - "traefik.http.routers.chat.entrypoints=websecure"
      - "traefik.http.routers.chat.tls=true"
      - "traefik.http.routers.chat.tls.certresolver=myresolver"
      - "traefik.http.services.chat.loadbalancer.server.port=8080"
    environment:
      - PORT=8080  # USE_POST를 PORT로 수정
    networks:
      - network

networks:
  network:

    